`Made Easy Arch` -> `Tarch` rebrand

diff --git a/releng/airootfs/usr/bin/tarchinstall b/releng/airootfs/usr/bin/tarchinstall
--- a/releng/airootfs/usr/bin/tarchinstall
+++ b/releng/airootfs/usr/bin/tarchinstall
@@ -9,12 +9,12 @@ if [[ "$skipArchInstall" == "false" ]] then
     if [[ "$skipWait" == "true" ]]; then
         archinstall
     else
-        echo "|>|> [90mMade Easy [36mArch [97m- [34mThe Installer [97m<|<|"
+        echo "|>|> [90mT[36march[97m- [34mThe Installer [97m<|<|"
         echo
-        echo "Hey! Looks like you're ready to install Made Easy Arch!"
+        echo "Hey! Looks like you're ready to install Tarch!"
         echo "Here's what you need to do:"
-        echo "  - When done installing, don't reboot from archinstall. Just exit the install, and meainstall will do postinstall setup."
-        echo "  - Made Easy Arch is in early beta! But the dotfiles should be just fine to use daily."
+        echo "  - When done installing, don't reboot from archinstall. Just exit the install, and tarchinstall will do postinstall setup."
+        echo "  - Tarch is in early beta! But the dotfiles should be just fine to use daily."
         echo "  - If you encounter any issues, please open an issue on the GitHub repository."
         echo
         echo "Whenever you're ready, press enter to continue, ctrl + c to back out!"
@@ -35,12 +35,12 @@ cp -r /etc/skel/. /mnt/etc/skel/ && echo "Copied skel to /mnt/etc/skel/" || echo
 for userdir in /mnt/home/*/; do
     cp -r /etc/skel/. "$userdir" && echo "Copied skel to $userdir" || echo "Failed to copy skel"
 done
-cp -r /usr/share/madeeasyarch/ /mnt/usr/share/ && echo "Copied madeeasyarch to /mnt/usr/share/" || echo "Failed to copy madeeasyarch"
+cp -r /usr/share/tarch/ /mnt/usr/share/ && echo "Copied tarch to /mnt/usr/share/" || echo "Failed to copy tarch"
 
 # Installing pre-packages
 echo && figlet "Installing pre-packages" || echo "== Installing pre-packages =="
-arch-chroot /mnt pacman -S --noconfirm $(< /usr/share/madeeasyarch/pre-packages/pacman.txt) && echo "Pre-packages pacman installed" || echo "Failed to install pre-packages pacman"
-arch-chroot /mnt nix profile install --impure $(< /usr/share/madeeasyarch/pre-packages/nix.txt) && echo "Pre-packages nix installed" || echo "Failed to install pre-packages nix"
+arch-chroot /mnt pacman -S --noconfirm $(< /usr/share/tarch/pre-packages/pacman.txt) && echo "Pre-packages pacman installed" || echo "Failed to install pre-packages pacman"
+arch-chroot /mnt nix profile install --impure $(< /usr/share/tarch/pre-packages/nix.txt) && echo "Pre-packages nix installed" || echo "Failed to install pre-packages nix"
 arch-chroot /mnt chsh -s /usr/bin/zsh && echo "Shell changed to zsh" || echo "Failed to change shell"
 
 # Finalize
